---
<<<<<<< HEAD:playbook/apache11.yaml
- hosts: webserver11
=======
- hosts: webservers
>>>>>>> 12c1fc26fb4f22462414951346b973bff7a4e224:playbook/apache.yaml
  remote_user: ansible
  become: yes

  tasks:
  - name: install latest apache
    yum:
      name: httpd
      state: latest

  - name: write apache config file
    template:
      src: /ansible/templates/httpd11.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart httpd

  - name: web content
    template:
      src: /ansible/templates/webserver11index1.html.j2
      dest: /var/www/html/index11.html

  - name: ensure apache server is running
    service:
      name: httpd
      state: started

  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
