---
- hosts: loadbalancer6
  remote_user: ansible
  become: yes

  tasks:
  - name: install latest haproxy
    yum:
      name: haproxy
      state: latest

  - name: write haproxy config file
    template:
      src: /ansible/templates/haproxy6.conf.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
    - restart haproxy

  - name: ensure haproxy server is running
    service:
      name: haproxy
      state: started

  handlers:
  - name: restart haproxy
    service:
      name: haproxy
      state: restarted

